
INSERT INTO niveau VALUES (1, 'CP');
INSERT INTO niveau VALUES (2, 'CE1');
INSERT INTO niveau VALUES (3, 'CE2');
INSERT INTO niveau VALUES (4, 'CM1');
INSERT INTO niveau VALUES (5, 'CM2');

INSERT INTO matiere VALUES (1, 'Francais', 1);
INSERT INTO matiere VALUES (2, 'Mathematiques', 1);
INSERT INTO matiere VALUES (3, 'Histoire', 1);
INSERT INTO matiere VALUES (4, 'Geographie', 1);
INSERT INTO matiere VALUES (5, 'EMC', 1);
INSERT INTO matiere VALUES (6, 'Anglais', 1);
INSERT INTO matiere VALUES (7, 'SVT', 1);
INSERT INTO matiere VALUES (8, 'Francais', 2);
INSERT INTO matiere VALUES (9, 'Mathematiques', 2);
INSERT INTO matiere VALUES (10, 'Histoire', 2);
INSERT INTO matiere VALUES (11, 'Geographie', 2);
INSERT INTO matiere VALUES (12, 'EMC', 2);
INSERT INTO matiere VALUES (13, 'Anglais', 2);
INSERT INTO matiere VALUES (14, 'SVT', 2);
INSERT INTO matiere VALUES (15, 'Francais', 3);
INSERT INTO matiere VALUES (16, 'Mathematiques', 3);
INSERT INTO matiere VALUES (17, 'Histoire', 3);
INSERT INTO matiere VALUES (18, 'Geographie', 3);
INSERT INTO matiere VALUES (19, 'EMC', 3);
INSERT INTO matiere VALUES (20, 'Anglais', 3);
INSERT INTO matiere VALUES (21, 'SVT', 3);
INSERT INTO matiere VALUES (22, 'Francais', 4);
INSERT INTO matiere VALUES (23, 'Mathematiques', 4);
INSERT INTO matiere VALUES (24, 'Histoire', 4);
INSERT INTO matiere VALUES (25, 'Geographie', 4);
INSERT INTO matiere VALUES (26, 'EMC', 4);
INSERT INTO matiere VALUES (27, 'Anglais', 4);
INSERT INTO matiere VALUES (28, 'SVT', 4);
INSERT INTO matiere VALUES (29, 'Francais', 5);
INSERT INTO matiere VALUES (30, 'Mathematiques', 5);
INSERT INTO matiere VALUES (31, 'Histoire', 5);
INSERT INTO matiere VALUES (32, 'Geographie', 5);
INSERT INTO matiere VALUES (33, 'EMC', 5);
INSERT INTO matiere VALUES (34, 'Anglais', 5);
INSERT INTO matiere VALUES (35, 'SVT', 5);


INSERT INTO exercice VALUES (1, NULL);
INSERT INTO exercice VALUES (2, NULL);
INSERT INTO exercice VALUES (3, NULL);
INSERT INTO exercice VALUES (4, NULL);
INSERT INTO exercice VALUES (5, NULL);
INSERT INTO exercice VALUES (6, NULL);
INSERT INTO exercice VALUES (7, NULL);
INSERT INTO exercice VALUES (8, NULL);

INSERT INTO utilisateur VALUES (1, 123456, 'toto', 'toto', 0612345678, 'toto@gmail.com');
INSERT INTO utilisateur VALUES (2, 123456, 'tata', 'tata', 0651515151,'tata@gmail.com');
INSERT INTO utilisateur VALUES (3, 123456, 'tutu', 'tutu', 0654964654,'tutu@gmail.com');
INSERT INTO utilisateur VALUES (4, 123456, 'titi', 'titi', 0651321654,'titi@gmail.com');
INSERT INTO utilisateur VALUES (5, 123456, 'bobo', 'bobo', 0651651954,'bobo@gmail.com');
INSERT INTO utilisateur VALUES (6, 123456, 'baba', 'baba', 0651561546,'baba@gmail.com');
INSERT INTO utilisateur VALUES (7, 123456, 'bubu', 'bubu', 0654161321,'bubu@gmail.com');
INSERT INTO utilisateur VALUES (8, 123456, 'bibi', 'bibi', 0654165161,'bibi@gmail.com');
INSERT INTO utilisateur VALUES (9, 123456, 'vava', 'vava', 0651312418,'vava@gmail.com');
INSERT INTO utilisateur VALUES (10, 123456, 'vivi', 'vivi',0654151231, 'vivi@gmail.com');